name: "ShopGUIPlus-SellGUI"
main: "net.mackenziemolloy.SGPSellGUI.Main"
authors: ["Mackenzie Molloy"]
version: "1.0.0"
api-version: "1.15"
softdepend: [ShopGUIPlus]

commands:
  sellgui:
    aliases: [sg, sell]
    description: Sell COmmand
